project_id = "hywvxiezdxhvfwqzlcdj"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]

[functions.reservation-confirmation]
verify_jwt = false

[functions.reservation-status]
verify_jwt = false