project_id = "hywvxiezdxhvfwqzlcdj"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]

[functions.send-reservation-emails]
verify_jwt = false

[functions.send-status-email]
verify_jwt = false